name: parttec
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  image_picker: ^1.1.0
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2   # ✅ آخر نسخة متوافقة مع Dart 3.3
  fl_chart: ^0.68.0
  file_picker: ^8.0.0
  dropdown_search: ^5.0.6

  flutter_local_notifications: 18.0.1
  shared_preferences_platform_interface: any
  shared_preferences_foundation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
